env:
  KUBE_CONTEXT: nuc
  APP: sandbox-express
  TAG: ${BUILDKITE_COMMIT}
  IMAGE: jordanyong/${APP}:${TAG}
steps:
  - command: ls
    plugins:
      - ssh://git@github.com:obrin/buildkite-deploy-plugin.git#v1.0.0:
          pattern: "*.md"

  # - label: ":rocket: Deploying to development"
  #   branches: "deploy/*"
  #   plugins:
  #     - ssh://git@github.csnzoo.com/secure/deploy-buildkite-plugin.git#v<maj>.<min>.<patch>:
  #         environment: "dev"
  #   agents:
  #     queue: docker_prod
